### ISSUE TITLE
How does it run with KOReader?

### ISSUE THREAD

**Issue by proppp** [bjesus/air#1]
Hey! This project is amazing! I'm planning on installing this on my Clara as soon as i have free time. Have you tried installing [KOReader](https://koreader.rocks/)? I'd really like to know how it behaves with it (make sure you check it out, it's an awesome interface): if it's reasonably usable, then I'm all sold! ^_^

**Comment by m040601** [comment]
Like the previous commenter, I'm also quite amazed and intrigued by this project. I'm also a Koreader user on the Kobo Clara HD, and curious about it's possible behaviour/relation with air.

But the last update seems to be July 2022.

Could the maintainer, bjesus, provide any updates ?

- Are you actually using this daily ?
- What's working, what's not ?
- Is it planned to continue ?

Thansk in advance.

**Comment by bjesus** [comment]
Hey! sorry, I've been busy with many other projects recently.

Unfortunately I didn't manage to get KOReader working yet. I agree this would be the real killer feature, because while Foliate works, it's very limited and very slow as it uses WebKit. From what I know, the issue mostly stems from pmOS using musl and not libc, but i'm not sure and probably there are other issues too. I know that @akemnade has been working on it, and he managed to get KOReader running on the Clara HD with Debian. I've been considering restarting the work on AIR and this time basing it on Debian, but didn't get the time to do so.

@m040601 - I am using it, not really daily but every once in a while. the readme should reflect pretty well what's working and what's not. I do plan to continue but can't really give any ETA unfortunately.

**Comment by akemnade** [comment]
There are two different things: Installing KOReader on a system and having it as a part of a distribution.
I really would prefer to have it as part of a distribution in a maintainable state, so it can be just included in the installation process.
Installing it on pmOS directly would probably just need to collect some patches from the corresponding aports thing. If we need some proof of concept thing, I would try that first.
And pmOS is smaller than debian, so that would be the first choice.

**Comment by akemnade** [comment]
getting that into distribution would require KOReader to use supplied libraries and not bring its own versions, that would need more work. That design decision is really sane for what KOReader has started. Some more extended reader of Kindle so it needs to exist in a hostile environment. But for a friendly environment we need an option to be more cooperative.

**Comment by bjesus** [comment]
I'm happy to say I finally got KOReader working using a Debian chroot! It's definitely not as nice as having it as part of the distribution, but it works, and it's x100 times more performant than Foliate. Installation was pretty straightforward, mostly this:

```sh
$ sudo apk add debootstrap xhost
$ sudo debootstrap  unstable ~/chroot http://http.debian.net/debian/
$ cp koreader-2023.03-armhf.deb ~/chroot/root
$ mkdir -p ~/chroot/tmp/.X11-unix
$ sudo mount --bind /tmp/.X11-unix ~/chroot/tmp/.X11-unix
$ xhost + local:
$ sudo chroot ~/chroot /bin/bash
# inside the chroot:
$ apt update && apt install libsdl2-2.0-0 fonts-noto-hinted fonts-droid-fallback 
$ sudo dpkg -i /root/koreader-2023.03-armhf.deb
$ DISPLAY=:0 koreader
```

I'll update this project with more details later.

In terms of space, Debian takes about 500mb with KOReader, fonts and all the dependencies. So the original 8GB sdcard still has 5GB of free space for books and whatnot after installing pmOS and koreader.

**Comment by m040601** [comment]
Great work !

> I'll update this project with more details later.

Can you please add one or two lines to the README about it's "relation" to PostmarketOS ? It would help readers who find your repo understand better what it's purpose is. Maybe they already know about PostmarketOS and Koreader. Or maybe not. These are all questions, that maybe are "obvious" to you the creator, but not others. Examples:


- Why would you want to install "air" ?
- Debian (chroot ?) versus PostmarketOS
- What does it do different than a "bare" PostmarketOS ?
- What is it possible with "air" that is not possible with PostmarketOS ?
- What does it bring to the table running Koreader on top of the factory Kobo Clara, versus, running Koreader in air ?
- Why did you choose AwesomeWM and not xyz ?
- How to revert back to a pristine factory state if you want to test it and then uninstall it ?
- etc ...


If you manage to find the time could you eventually post a video to youtube or so actually using it ? Booting, reading some documents and running some apps?

Thanks.


PS: PostmarketOS seems to be quite active on, https://wiki.postmarketos.org/wiki/Kobo_Clara_HD_(kobo-clara)

So I expect many further exciting developments.

**Comment by bjesus** [comment]
Hey, closing this issue now because I've been using KOReader quite smoothly recently, so the answer is yes - you can use KOReader. I've updated the README with some more information, but here are some more specific answers to your questions:

- one would want to use AIR if they run PostmarketOS on the Clara simply because AFAIK it's the fastest way to get your device to a useful state. Sure there are many other interfaces, but some require a mouse, a keyboard, more hardware buttons etc.
- Debian chroot essentially means you have two systems installed on your device (Debian & pmOS). I don't think there's much performance issues with it, but it does take more space. I don't know that anyone managed to run KOReader on directly on pmOS, but I also don't have a clear idea of how to install Debian on the Clara, so installing pmOS and a Debian chroot was the path I chose.
- the difference from "bare" pmOS is kinda like asking what's the different between GNOME and Debian. Currently AIR is mostly an interface, with some shortcuts that are specific to the Clara. pmOS gives you a running linux system (that's a lot!!!) and AIR gives you a configuration for starting to use your device as an ereader.
- nothing is "impossible" without AIR, because it's just a collection of scripts and configuration files. 
- Running KOReader in AIR means you have a linux device. You can also run a browser, you can SSH into your device, sync files using syncthing and whatnot. KOReader is just one app you can run. You can't run emacs inside factory Kobo Clara AFAIK :)
- I chose AwesomeWM because I think a tilling wm works great for tablets, and AwesomeWM has a easily configurable lua system for creating widgets, which I'm using for creating some configuration panels. It's a little heavier on memory than i3, for example, but I haven't had any issues with that so far. Maybe one day it would be nice to convert it.
- Not sure if you mean revert to clean pmOS or to original firmware. for the former, just undo the steps from the AIR README. For the latter, make sure that you keep an image of your sdcard before you write pmOS to it, and if you'll ever want to revert I'm pretty sure you'll just need to write it back to the card. note that I haven't tried it.

I'll try to make some video later and update here.

**Comment by akemnade** [comment]
well, disadvantage of deb chroot is probably also the amount of RAM needed.
But it is a proof that having koreader on top of pmOS is worth some effort.

**Comment by m040601** [comment]
Thanks for taking the time to elaborate these things.
It's much more clear now where Air "fits" in the middle of all these things, with all the "why's" and "why not"s.

This is really interesting stuff. It doesnt deserve to be "hidden" in a github issue or README. You should really consider putting AIR in a section of your blog or website, to make it better known.



> ... Debian chroot essentially means you have two systems installed on your device (Debian & pmOS)
> ... I.don't know that anyone managed to run KOReader on directly on pmOS,
> .... .don't have a clear idea of how to install Debian on the Clara, so installing pmOS and a Debian chroot was the path I chose.


I think I am much more elucidated now.

That one first got me confused as why the need for the "Debian" salad thing mixed with PostmarketOS. 

So I guess this all thing must be because PmOS is based on Alpine Linux. Which is  a busybox/musl minimal thing. But it is not a traditional glibc/systemd Linux distro. And that might bring a lot of not so easy to solve incompatibilities.

Koreader itself brings lotz of dependencies.
And this must be then the reason why, it is not an easy peasy thing to just slap Koreader on top of PMOs.

**Comment by m040601** [comment]
> You can use any Linux application with it, for example:
> 
>     KOReader or Foliate for ebooks
>     Firefox for (slow) web
>     Castor for Gopher and Gemini
>     St for terminal
> 

Hmmm nice ... st ... dwm ... my old companions ... cant wait to meet you in black and white e-ink.

Never thought I would see the day, running "real" Linux things on my Kobo Clara.
Best 99 euros I invested 3 years ago ...

Apropos browsers

Yeah, as a gemini reader an e-ink device makes a lot of sense. Much more than for the traditional "bloated" web pages. Isnt Castor dependent or Rust ? Never imagined you could run Rust applications on my Kobo Clara.

I'm a terminal fanatic person. Avoid GUIs as much as possible.
But there is this other Gemini client which is just a simple marvel of beauty and engineering. Lagrange. It is so much well thought. I think its a C/C++ thing and heavy on graphical libraries, so wonder if it could make it to the Clara .


Another one I cant wait to try out and consider a "killer" app, is a simple graphical or terminal client for the mpd music playerd daemon.

Something to simply scroll playlists or read the metadata about the currently playing track without having to pull a smartphone or turn on a pc.

**Comment by bjesus** [comment]
There are no issues with running Rust based applications on the Clara. I have actually built https://github.com/bjesus/pidif in Rust specifically for the Clara, and once I even compiled it directly on the Clara (it took quite some time...).

At the end of the day, we'll have to draw the line somewhere with AIR and say "okay, we give you a usable Linux-based e-reader environment, now you go ahead and do you". For example, I have a script downloading RSS feeds and putting them as HTMLs so I can read them with KOReader, but it's probably a little too specific for my use case and shouldn't be part of AIR. You can install any MPD client you want - it's simply Linux. KOReader was very hard to get running, but other than that it was mostly straightforward. Alpine actually has many applications packed.

**Comment by m040601** [comment]
> I have actually built ... in Rust specifically for the Clara,

Yes, I noticed . You seem to have a lot of interesting hidden and future treasures waiting to be discovered ... :-)

> Alpine actually has many applications packed.

Yes, and I am lately utterly fascinated by it. And replacing all my Raspberry Pis and small Arm chromebooks and boards with it. And I say this as a loyal power Archlnux user.

> You can install any xxx client you want - it's simply Linux

Yes, I am slowly trying to convince my self of that.But I am also a chicken. So that's why I havent yet had the "guts" to install PostmarketOS on my Kobo Clara. Even in an extra SD card.

I've been happy in the last years with Koreader and https://github.com/pgaskin/NickelMenu. Just leave the Kobo factory there unused . I boot the Clara, bypass the Kobo interface and go straight to Koreader. Been rock solid without any glitches. And constantly improving. Koreader is an amazing community. But as anything community maintained I cant have any 100% guaranties of something breaking. But I just want to read. I want to pull it from my pocket and rely on it. I dont want to be constantly hacking and experimenting on the device.

I've been following that Kobo devices page on PMos for months. Waiting for it to go from "Testing" to "Community"

Untill then, I want to see "real life" videos on youtube of the thing working flawlessly.

> At the end of the day, we'll have to draw the line somewhere with AIR and say ... xyz

Yes, I understand your point.


Basicly in the end this all means that you can get completely rid of Kobo factory interface stuff, and have a 100% free Kobo Clara. (hmm ...maybe except some one or two firmware blobs)


Some more suggestions for the README.

Change the opening sentence from,

> AIR is a graphical interface for e-readers that heavily relies on AwesomeWM. It's tested on the Kobo Clara HD using PostmarketOS, but perhaps it can be used elsewhere. It is a work in progress.

To something like,

> AIR is a graphical interface for e-readers that runs on top of PostmarketOS. 
> It heavily relies on AwesomeWM and brings that desktop experience adapted to a small e-ink device. Other applications such as KOReader can also be part of it. 
> 
> It's tested on the Kobo Clara HD, but perhaps it can be used elsewhere. It is a work in progress.
>

**Comment by bjesus** [comment]
@m040601 to be honest, if you're happy with the setup now, and it fulfill all your needs, I wouldn't switch. I'm using it daily and it works very well for me, but some things aren't 100% smooth all the time. I suspect battery usage is a bit higher, though it's very hard to say. Putting the device to sleep sometimes takes a few attempts.

It's worth it if you think you might want to do _more_ with your Clara (e.g. mpd client? home assistant client? syncthing? rsync? ssh? web?), but if those use cases aren't appealing to you - I don't see a very good reason to change.

**Comment by anaxonda** [comment]
Hello, question about running koreader on PMOS with AIR. Do the default koreader gestures interfere with the AIR gestures? Would they need to be remapped, or have AIR gestures be disable when koreader is running?

I'd love to have my Clara be simple reliable koreader most of the time, but with access to a full linux environment, especially for eink writing environment.
