### ISSUE TITLE
description of the architecture of this program

### ISSUE THREAD

**Issue by Szybet** [bjesus/air#5]
Hello
I'm thinking of replacing the current xorg implementation on [InkBox OS](https://github.com/Kobo-InkBox/inkbox) with this program. To do that I would need to know how this program works. Reading the lua code doesn't help me... Could you in detail describe how and what it's doing? maybe a video of running this program? Some details I would like to know:
- What / How it's outputting things on the screen? Just putting it in framebuffer?
- Touch is managed by xorg, right?
- Is it restarting the input drivers?...
```
        echo 1-0024 | sudo tee /sys/bus/i2c/drivers/cyttsp5/unbind
	sleep 1
        echo 1-0024 | sudo tee /sys/bus/i2c/drivers/cyttsp5/bind
```
- Are there any problems with apps crashing? Something like that?

Thanks!

**Comment by bjesus** [comment]
Hey @Szybet . AIR is just a GUI layer. It uses Awesome WM, with Xorg, to draw stuff on the screen. Touch is indeed handled by XOrg too. It indeed restarts the input drivers upon waking up from sleep, because it seemed to be frozen otherwise.

I actually haven't experienced app crashing. The device does have a low RAM, so I suspect that running memory heavy software could lead to that, however.

Let me know if you have more questions. I'm closing this issue though because it doesn't seem to be an issue really.
